#**MACHINE LEARNING PROJECT ON RED WINE DATASET**

# Classification

**Data preprocessing**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('/content/RED WINE.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [4]:
dataset['quality'].unique()

array([5, 6, 7, 4, 8, 3])

**Separate features and target**  


In [5]:
X = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

**Splitting data into train and test sets**

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.20)

**Standardization**

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
sc = StandardScaler()

In [10]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Train on different algorithms**

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [12]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [13]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [17]:
l_c

array([[  0,   7,   6,   0,   0],
       [  0, 104,  40,   0,   0],
       [  0,  36,  69,   8,   0],
       [  0,   4,  29,  14,   0],
       [  0,   0,   2,   1,   0]])

In [18]:
k_c

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  5,  0,  0],
       [ 1,  2, 91, 48,  2,  0],
       [ 0,  0, 38, 61, 14,  0],
       [ 0,  0, 11, 19, 17,  0],
       [ 0,  0,  0,  1,  2,  0]])

In [19]:
d_c

array([[ 0,  0,  0,  0,  0,  0],
       [ 1,  3,  5,  4,  0,  0],
       [ 2,  4, 92, 40,  2,  4],
       [ 1,  2, 27, 67, 13,  3],
       [ 0,  0,  9, 16, 20,  2],
       [ 0,  0,  0,  0,  3,  0]])

In [20]:
r_c

array([[  0,   0,   0,   0,   0,   0],
       [  1,   0,   8,   4,   0,   0],
       [  0,   0, 112,  31,   1,   0],
       [  0,   0,  25,  80,   8,   0],
       [  0,   0,   3,  19,  24,   1],
       [  0,   0,   0,   2,   1,   0]])

In [21]:
s_c

array([[  0,   7,   6,   0,   0],
       [  0, 101,  43,   0,   0],
       [  0,  41,  72,   0,   0],
       [  0,   5,  42,   0,   0],
       [  0,   0,   3,   0,   0]])

In [22]:
ks_c

array([[  0,   8,   5,   0,   0],
       [  0, 106,  38,   0,   0],
       [  0,  34,  73,   6,   0],
       [  0,   5,  25,  17,   0],
       [  0,   0,   2,   1,   0]])

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

**Result**

In [25]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.584375
KNN: 0.528125
Decision Tree: 0.56875
Random Forest: 0.675
Linear SVC: 0.540625
Kernel SVC: 0.584375


#Regression

**Data preprocessing**

In [26]:
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt

In [27]:
data=pd.read_csv("/content/RED WINE.csv")

In [28]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [29]:
data. describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [30]:
data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [31]:
data. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


**Separate features and target**

In [32]:
X = data.iloc[: , :-1].values
Y = data.iloc[: , -1].values

In [33]:
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [34]:
Y

array([5, 5, 5, ..., 6, 5, 6])

**Splitting Data into Train and Test sets**

In [35]:
 from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [37]:
X_train

array([[ 7.5  ,  0.38 ,  0.57 , ...,  3.36 ,  0.55 , 11.4  ],
       [ 6.   ,  0.64 ,  0.05 , ...,  3.52 ,  0.78 , 10.6  ],
       [ 8.3  ,  0.705,  0.12 , ...,  3.51 ,  0.72 , 10.   ],
       ...,
       [11.7  ,  0.28 ,  0.47 , ...,  3.15 ,  0.67 , 10.6  ],
       [ 7.5  ,  0.41 ,  0.15 , ...,  3.14 ,  0.58 ,  9.1  ],
       [10.4  ,  0.43 ,  0.5  , ...,  3.1  ,  0.87 , 11.4  ]])

**Train on different algorithms**

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [39]:
m_reg = LinearRegression()
p_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
r_reg = RandomForestRegressor(n_estimators=500)

In [40]:
X_poly = PolynomialFeatures(degree =2)
X_poly = X_poly.fit_transform(X_train)

In [41]:
m_reg.fit(X_train, Y_train)
p_reg.fit(X_poly,Y_train)
d_reg.fit(X_train, Y_train)
r_reg.fit(X_train, Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=500, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [42]:
temp = PolynomialFeatures(degree =2)
temp = temp.fit_transform(X_test)

In [43]:
m_pred = m_reg.predict(X_test)
p_pred = p_reg.predict(temp)
d_pred = d_reg.predict(X_test)
r_pred = r_reg.predict(X_test)

In [44]:
from sklearn.metrics import r2_score

In [45]:
m = r2_score(Y_test, m_pred)
p = r2_score(Y_test, p_pred)
d = r2_score(Y_test, d_pred)
r = r2_score(Y_test, r_pred)

**Result**

In [46]:
print('Logistic Regression: ' + str(m) + '\npolyfeat: ' + str(p) + '\nDecision Tree: ' + str(d) + '\nRandom Forest: ' + str(r))

Logistic Regression: 0.37321666289855704
polyfeat: 0.2908387469536111
Decision Tree: -0.03262331045219735
Random Forest: 0.4888054824145496


##**Conclusion**


according to given dataset,wine quality will be good if it cross the scale above 75%.

after testing on them the purity value obtained are less than given reference value.hence, the given the quality of wine is not good..

Since Random forest is giving more efficiency than other algorithm we can consider random forest as the best algorithm for this dataset